create table if not exists feeding_events (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  farm_id text not null,
  pond_id text not null,
  mode text not null,
  amount_kg numeric not null,
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists water_readings (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  farm_id text not null,
  pond_id text not null,
  temperature numeric,
  ph numeric,
  dissolved_oxygen numeric,
  turbidity numeric,
  ammonia numeric,
  nitrite numeric,
  raw_payload jsonb,
  created_at timestamptz not null default now()
);

create table if not exists finance_income (
  id bigint generated by default as identity primary key,
  farm_id text not null,
  date date not null,
  buyer text not null,
  quantity_kg numeric not null,
  price_per_kg numeric not null,
  total numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists finance_expenses (
  id bigint generated by default as identity primary key,
  farm_id text not null,
  date date not null,
  category text not null,
  description text not null,
  amount numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_water_readings_farm_pond_time on water_readings (farm_id, pond_id, timestamp desc);
create index if not exists idx_income_farm_date on finance_income (farm_id, date desc);
create index if not exists idx_expenses_farm_date on finance_expenses (farm_id, date desc);
