/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as HatcheryIndexRouteImport } from './routes/hatchery.index'
import { Route as CagesIndexRouteImport } from './routes/cages.index'
import { Route as WaterLiveRouteImport } from './routes/water.live'
import { Route as WaterHistoryRouteImport } from './routes/water.history'
import { Route as WaterAlertsRouteImport } from './routes/water.alerts'
import { Route as SettingsUsersAndRolesRouteImport } from './routes/settings.users-and-roles'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsFarmRouteImport } from './routes/settings.farm'
import { Route as SettingsDevicesRouteImport } from './routes/settings.devices'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinancePnlRouteImport } from './routes/finance.pnl'
import { Route as FinanceIncomeRouteImport } from './routes/finance.income'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FeedingScheduleRouteImport } from './routes/feeding.schedule'
import { Route as FeedingManualRouteImport } from './routes/feeding.manual'
import { Route as FeedingInventoryRouteImport } from './routes/feeding.inventory'
import { Route as FeedingHistoryRouteImport } from './routes/feeding.history'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AiInsightsRouteImport } from './routes/ai.insights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const HatcheryIndexRoute = HatcheryIndexRouteImport.update({
  id: '/hatchery/',
  path: '/hatchery/',
  getParentRoute: () => rootRouteImport,
} as any)
const CagesIndexRoute = CagesIndexRouteImport.update({
  id: '/cages/',
  path: '/cages/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterLiveRoute = WaterLiveRouteImport.update({
  id: '/water/live',
  path: '/water/live',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterHistoryRoute = WaterHistoryRouteImport.update({
  id: '/water/history',
  path: '/water/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterAlertsRoute = WaterAlertsRouteImport.update({
  id: '/water/alerts',
  path: '/water/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersAndRolesRoute = SettingsUsersAndRolesRouteImport.update({
  id: '/settings/users-and-roles',
  path: '/settings/users-and-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFarmRoute = SettingsFarmRouteImport.update({
  id: '/settings/farm',
  path: '/settings/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/settings/devices',
  path: '/settings/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePnlRoute = FinancePnlRouteImport.update({
  id: '/finance/pnl',
  path: '/finance/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIncomeRoute = FinanceIncomeRouteImport.update({
  id: '/finance/income',
  path: '/finance/income',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingScheduleRoute = FeedingScheduleRouteImport.update({
  id: '/feeding/schedule',
  path: '/feeding/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingManualRoute = FeedingManualRouteImport.update({
  id: '/feeding/manual',
  path: '/feeding/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingInventoryRoute = FeedingInventoryRouteImport.update({
  id: '/feeding/inventory',
  path: '/feeding/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingHistoryRoute = FeedingHistoryRouteImport.update({
  id: '/feeding/history',
  path: '/feeding/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai/insights',
  path: '/ai/insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai/insights': typeof AiInsightsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feeding/history': typeof FeedingHistoryRoute
  '/feeding/inventory': typeof FeedingInventoryRoute
  '/feeding/manual': typeof FeedingManualRoute
  '/feeding/schedule': typeof FeedingScheduleRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/pnl': typeof FinancePnlRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/farm': typeof SettingsFarmRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/users-and-roles': typeof SettingsUsersAndRolesRoute
  '/water/alerts': typeof WaterAlertsRoute
  '/water/history': typeof WaterHistoryRoute
  '/water/live': typeof WaterLiveRoute
  '/cages/': typeof CagesIndexRoute
  '/hatchery/': typeof HatcheryIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai/insights': typeof AiInsightsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feeding/history': typeof FeedingHistoryRoute
  '/feeding/inventory': typeof FeedingInventoryRoute
  '/feeding/manual': typeof FeedingManualRoute
  '/feeding/schedule': typeof FeedingScheduleRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/pnl': typeof FinancePnlRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/farm': typeof SettingsFarmRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/users-and-roles': typeof SettingsUsersAndRolesRoute
  '/water/alerts': typeof WaterAlertsRoute
  '/water/history': typeof WaterHistoryRoute
  '/water/live': typeof WaterLiveRoute
  '/cages': typeof CagesIndexRoute
  '/hatchery': typeof HatcheryIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/production': typeof ProductionIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai/insights': typeof AiInsightsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feeding/history': typeof FeedingHistoryRoute
  '/feeding/inventory': typeof FeedingInventoryRoute
  '/feeding/manual': typeof FeedingManualRoute
  '/feeding/schedule': typeof FeedingScheduleRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/pnl': typeof FinancePnlRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/farm': typeof SettingsFarmRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/users-and-roles': typeof SettingsUsersAndRolesRoute
  '/water/alerts': typeof WaterAlertsRoute
  '/water/history': typeof WaterHistoryRoute
  '/water/live': typeof WaterLiveRoute
  '/cages/': typeof CagesIndexRoute
  '/hatchery/': typeof HatcheryIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai/insights'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/feeding/history'
    | '/feeding/inventory'
    | '/feeding/manual'
    | '/feeding/schedule'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/pnl'
    | '/finance/reports'
    | '/settings/devices'
    | '/settings/farm'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/users'
    | '/settings/users-and-roles'
    | '/water/alerts'
    | '/water/history'
    | '/water/live'
    | '/cages/'
    | '/hatchery/'
    | '/inventory/'
    | '/production/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai/insights'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/feeding/history'
    | '/feeding/inventory'
    | '/feeding/manual'
    | '/feeding/schedule'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/pnl'
    | '/finance/reports'
    | '/settings/devices'
    | '/settings/farm'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/users'
    | '/settings/users-and-roles'
    | '/water/alerts'
    | '/water/history'
    | '/water/live'
    | '/cages'
    | '/hatchery'
    | '/inventory'
    | '/production'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/ai/insights'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/feeding/history'
    | '/feeding/inventory'
    | '/feeding/manual'
    | '/feeding/schedule'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/pnl'
    | '/finance/reports'
    | '/settings/devices'
    | '/settings/farm'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/users'
    | '/settings/users-and-roles'
    | '/water/alerts'
    | '/water/history'
    | '/water/live'
    | '/cages/'
    | '/hatchery/'
    | '/inventory/'
    | '/production/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  FeedingHistoryRoute: typeof FeedingHistoryRoute
  FeedingInventoryRoute: typeof FeedingInventoryRoute
  FeedingManualRoute: typeof FeedingManualRoute
  FeedingScheduleRoute: typeof FeedingScheduleRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceIncomeRoute: typeof FinanceIncomeRoute
  FinancePnlRoute: typeof FinancePnlRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsFarmRoute: typeof SettingsFarmRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsUsersAndRolesRoute: typeof SettingsUsersAndRolesRoute
  WaterAlertsRoute: typeof WaterAlertsRoute
  WaterHistoryRoute: typeof WaterHistoryRoute
  WaterLiveRoute: typeof WaterLiveRoute
  CagesIndexRoute: typeof CagesIndexRoute
  HatcheryIndexRoute: typeof HatcheryIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatchery/': {
      id: '/hatchery/'
      path: '/hatchery'
      fullPath: '/hatchery/'
      preLoaderRoute: typeof HatcheryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cages/': {
      id: '/cages/'
      path: '/cages'
      fullPath: '/cages/'
      preLoaderRoute: typeof CagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water/live': {
      id: '/water/live'
      path: '/water/live'
      fullPath: '/water/live'
      preLoaderRoute: typeof WaterLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water/history': {
      id: '/water/history'
      path: '/water/history'
      fullPath: '/water/history'
      preLoaderRoute: typeof WaterHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water/alerts': {
      id: '/water/alerts'
      path: '/water/alerts'
      fullPath: '/water/alerts'
      preLoaderRoute: typeof WaterAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users-and-roles': {
      id: '/settings/users-and-roles'
      path: '/settings/users-and-roles'
      fullPath: '/settings/users-and-roles'
      preLoaderRoute: typeof SettingsUsersAndRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/farm': {
      id: '/settings/farm'
      path: '/settings/farm'
      fullPath: '/settings/farm'
      preLoaderRoute: typeof SettingsFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/settings/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/pnl': {
      id: '/finance/pnl'
      path: '/finance/pnl'
      fullPath: '/finance/pnl'
      preLoaderRoute: typeof FinancePnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/income': {
      id: '/finance/income'
      path: '/finance/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof FinanceIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding/schedule': {
      id: '/feeding/schedule'
      path: '/feeding/schedule'
      fullPath: '/feeding/schedule'
      preLoaderRoute: typeof FeedingScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding/manual': {
      id: '/feeding/manual'
      path: '/feeding/manual'
      fullPath: '/feeding/manual'
      preLoaderRoute: typeof FeedingManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding/inventory': {
      id: '/feeding/inventory'
      path: '/feeding/inventory'
      fullPath: '/feeding/inventory'
      preLoaderRoute: typeof FeedingInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding/history': {
      id: '/feeding/history'
      path: '/feeding/history'
      fullPath: '/feeding/history'
      preLoaderRoute: typeof FeedingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/insights': {
      id: '/ai/insights'
      path: '/ai/insights'
      fullPath: '/ai/insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  FeedingHistoryRoute: FeedingHistoryRoute,
  FeedingInventoryRoute: FeedingInventoryRoute,
  FeedingManualRoute: FeedingManualRoute,
  FeedingScheduleRoute: FeedingScheduleRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceIncomeRoute: FinanceIncomeRoute,
  FinancePnlRoute: FinancePnlRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsFarmRoute: SettingsFarmRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsUsersAndRolesRoute: SettingsUsersAndRolesRoute,
  WaterAlertsRoute: WaterAlertsRoute,
  WaterHistoryRoute: WaterHistoryRoute,
  WaterLiveRoute: WaterLiveRoute,
  CagesIndexRoute: CagesIndexRoute,
  HatcheryIndexRoute: HatcheryIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
