-- AquaSmart initial Supabase schema for new projects.
-- Apply with: supabase db push after linking a new Supabase project.

create table if not exists feeding_events (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  pond_id text not null,
  mode text not null,
  amount_kg numeric not null,
  status text not null,
  farm_id text not null default 'default',
  created_at timestamptz not null default now()
);

create table if not exists water_readings (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  pond_id text not null,
  temperature numeric,
  ph numeric,
  dissolved_oxygen numeric,
  turbidity numeric,
  ammonia numeric,
  nitrite numeric,
  raw_payload jsonb,
  farm_id text not null default 'default',
  created_at timestamptz not null default now()
);

create table if not exists finance_income (
  id bigint generated by default as identity primary key,
  date date not null,
  buyer text not null,
  income_type text not null default 'Fish sale',
  unit text not null default 'kg',
  quantity numeric not null,
  unit_price numeric not null,
  quantity_kg numeric not null,
  price_per_kg numeric not null,
  total numeric not null,
  farm_id text not null default 'default',
  created_at timestamptz not null default now()
);

create table if not exists finance_expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null,
  description text not null,
  amount numeric not null,
  farm_id text not null default 'default',
  created_at timestamptz not null default now()
);

create table if not exists production_events (
  id uuid primary key,
  tenant_id text not null,
  cage_id text not null,
  type text not null check (type in ('stocking', 'mortality', 'harvest', 'sale', 'feeding')),
  fish_count numeric,
  weight_kg numeric,
  feed_kg numeric,
  created_at timestamptz not null default now()
);

create table if not exists inventory_items (
  id uuid primary key,
  tenant_id text not null,
  name text not null,
  category text not null check (category in ('feed', 'medicine', 'equipment', 'fuel', 'consumable')),
  unit text not null,
  quantity numeric not null default 0,
  low_stock_threshold numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists inventory_movements (
  id uuid primary key,
  tenant_id text not null,
  item_id uuid not null references inventory_items(id) on delete cascade,
  type text not null check (type in ('purchase', 'usage', 'adjustment')),
  quantity numeric not null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists cages (
  id uuid primary key,
  tenant_id text not null,
  name text not null,
  location text not null,
  fish_population numeric not null default 0,
  biomass_kg numeric not null default 0,
  status text not null check (status in ('active', 'maintenance')),
  created_at timestamptz not null default now()
);

create table if not exists hatchery_brooders (
  id uuid primary key,
  tenant_id text not null,
  name text not null,
  species text not null,
  status text not null check (status in ('active', 'paused')),
  created_at timestamptz not null default now()
);

create table if not exists hatchery_fingerling_batches (
  id uuid primary key,
  tenant_id text not null,
  brooder_id uuid references hatchery_brooders(id) on delete set null,
  quantity numeric not null,
  production_date date not null,
  growth_status text not null check (growth_status in ('early', 'mid', 'ready_for_transfer')),
  transferred_to_cage text,
  created_at timestamptz not null default now()
);

create index if not exists idx_water_readings_pond_time on water_readings (pond_id, timestamp desc);
create index if not exists idx_income_date on finance_income (date desc);
create index if not exists idx_expenses_date on finance_expenses (date desc);
create index if not exists idx_production_events_tenant_time on production_events (tenant_id, created_at desc);
create index if not exists idx_inventory_items_tenant_category on inventory_items (tenant_id, category);
create index if not exists idx_inventory_movements_tenant_time on inventory_movements (tenant_id, created_at desc);
create index if not exists idx_cages_tenant_status on cages (tenant_id, status);
create index if not exists idx_hatchery_brooders_tenant_status on hatchery_brooders (tenant_id, status);
create index if not exists idx_hatchery_batches_tenant_status on hatchery_fingerling_batches (tenant_id, growth_status);

-- Enable RLS
alter table if exists public.finance_income enable row level security;
alter table if exists public.finance_expenses enable row level security;
alter table if exists public.feeding_events enable row level security;
alter table if exists public.water_readings enable row level security;
alter table if exists public.production_events enable row level security;
alter table if exists public.inventory_items enable row level security;
alter table if exists public.inventory_movements enable row level security;
alter table if exists public.cages enable row level security;
alter table if exists public.hatchery_brooders enable row level security;
alter table if exists public.hatchery_fingerling_batches enable row level security;

-- Multi-tenant scope: each authenticated user only accesses their farm.
-- Older finance/IoT tables are scoped by farm_id derived from auth.uid().
-- Newer enterprise module tables are scoped by tenant_id and match backend-store tenantId(),
-- which uses the authenticated user's id.

create or replace function public.current_user_farm_id()
returns text
language sql
stable
as $$
  select case
    when auth.uid() is null then null
    else 'user_' || lower(auth.uid()::text)
  end
$$;

drop policy if exists "finance_income_select" on finance_income;
create policy "finance_income_select" on finance_income
for select using (farm_id = public.current_user_farm_id());
drop policy if exists "finance_income_insert" on finance_income;
create policy "finance_income_insert" on finance_income
for insert with check (farm_id = public.current_user_farm_id());
drop policy if exists "finance_income_update" on finance_income;
create policy "finance_income_update" on finance_income
for update using (farm_id = public.current_user_farm_id())
with check (farm_id = public.current_user_farm_id());
drop policy if exists "finance_income_delete" on finance_income;
create policy "finance_income_delete" on finance_income
for delete using (farm_id = public.current_user_farm_id());

drop policy if exists "finance_expenses_select" on finance_expenses;
create policy "finance_expenses_select" on finance_expenses
for select using (farm_id = public.current_user_farm_id());
drop policy if exists "finance_expenses_insert" on finance_expenses;
create policy "finance_expenses_insert" on finance_expenses
for insert with check (farm_id = public.current_user_farm_id());
drop policy if exists "finance_expenses_update" on finance_expenses;
create policy "finance_expenses_update" on finance_expenses
for update using (farm_id = public.current_user_farm_id())
with check (farm_id = public.current_user_farm_id());
drop policy if exists "finance_expenses_delete" on finance_expenses;
create policy "finance_expenses_delete" on finance_expenses
for delete using (farm_id = public.current_user_farm_id());

drop policy if exists "feeding_events_select" on feeding_events;
create policy "feeding_events_select" on feeding_events
for select using (farm_id = public.current_user_farm_id());
drop policy if exists "feeding_events_insert" on feeding_events;
create policy "feeding_events_insert" on feeding_events
for insert with check (farm_id = public.current_user_farm_id());

drop policy if exists "water_readings_select" on water_readings;
create policy "water_readings_select" on water_readings
for select using (farm_id = public.current_user_farm_id());
drop policy if exists "water_readings_insert" on water_readings;
create policy "water_readings_insert" on water_readings
for insert with check (farm_id = public.current_user_farm_id());

drop policy if exists "production_events_select" on production_events;
create policy "production_events_select" on production_events
for select using (tenant_id = auth.uid()::text);
drop policy if exists "production_events_insert" on production_events;
create policy "production_events_insert" on production_events
for insert with check (tenant_id = auth.uid()::text);

drop policy if exists "inventory_items_select" on inventory_items;
create policy "inventory_items_select" on inventory_items
for select using (tenant_id = auth.uid()::text);
drop policy if exists "inventory_items_insert" on inventory_items;
create policy "inventory_items_insert" on inventory_items
for insert with check (tenant_id = auth.uid()::text);
drop policy if exists "inventory_items_update" on inventory_items;
create policy "inventory_items_update" on inventory_items
for update using (tenant_id = auth.uid()::text)
with check (tenant_id = auth.uid()::text);
drop policy if exists "inventory_items_delete" on inventory_items;
create policy "inventory_items_delete" on inventory_items
for delete using (tenant_id = auth.uid()::text);

drop policy if exists "inventory_movements_select" on inventory_movements;
create policy "inventory_movements_select" on inventory_movements
for select using (tenant_id = auth.uid()::text);
drop policy if exists "inventory_movements_insert" on inventory_movements;
create policy "inventory_movements_insert" on inventory_movements
for insert with check (tenant_id = auth.uid()::text);

drop policy if exists "cages_select" on cages;
create policy "cages_select" on cages
for select using (tenant_id = auth.uid()::text);
drop policy if exists "cages_insert" on cages;
create policy "cages_insert" on cages
for insert with check (tenant_id = auth.uid()::text);
drop policy if exists "cages_update" on cages;
create policy "cages_update" on cages
for update using (tenant_id = auth.uid()::text)
with check (tenant_id = auth.uid()::text);
drop policy if exists "cages_delete" on cages;
create policy "cages_delete" on cages
for delete using (tenant_id = auth.uid()::text);

drop policy if exists "hatchery_brooders_select" on hatchery_brooders;
create policy "hatchery_brooders_select" on hatchery_brooders
for select using (tenant_id = auth.uid()::text);
drop policy if exists "hatchery_brooders_insert" on hatchery_brooders;
create policy "hatchery_brooders_insert" on hatchery_brooders
for insert with check (tenant_id = auth.uid()::text);
drop policy if exists "hatchery_brooders_update" on hatchery_brooders;
create policy "hatchery_brooders_update" on hatchery_brooders
for update using (tenant_id = auth.uid()::text)
with check (tenant_id = auth.uid()::text);
drop policy if exists "hatchery_brooders_delete" on hatchery_brooders;
create policy "hatchery_brooders_delete" on hatchery_brooders
for delete using (tenant_id = auth.uid()::text);

drop policy if exists "hatchery_fingerling_batches_select" on hatchery_fingerling_batches;
create policy "hatchery_fingerling_batches_select" on hatchery_fingerling_batches
for select using (tenant_id = auth.uid()::text);
drop policy if exists "hatchery_fingerling_batches_insert" on hatchery_fingerling_batches;
create policy "hatchery_fingerling_batches_insert" on hatchery_fingerling_batches
for insert with check (tenant_id = auth.uid()::text);
drop policy if exists "hatchery_fingerling_batches_update" on hatchery_fingerling_batches;
create policy "hatchery_fingerling_batches_update" on hatchery_fingerling_batches
for update using (tenant_id = auth.uid()::text)
with check (tenant_id = auth.uid()::text);
drop policy if exists "hatchery_fingerling_batches_delete" on hatchery_fingerling_batches;
create policy "hatchery_fingerling_batches_delete" on hatchery_fingerling_batches
for delete using (tenant_id = auth.uid()::text);

-- Security fix: ensure analytical views run with caller privileges (not definer).
-- Run in Supabase SQL editor.

DO $do$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_views WHERE schemaname = 'public' AND viewname = 'farmer_profit'
  ) THEN
    -- Force invoker semantics so RLS/user permissions are evaluated per caller.
    EXECUTE 'alter view public.farmer_profit set (security_invoker = true)';
  END IF;
END
$do$;
